<?php

/**
 * Implements hook_permission().
 */
function cornell_mixpanel_permission() {
  return [
    'administer cornell_mixpanel' => [
      'title' => t('Administer Cornell Mixpanel'),
      'description' => t('Set Mixpanel token and change other internal settings for Mixpanel integration.'),
    ],
  ];
}

/**
 * Implements hook_help().
 */
function cornell_mixpanel_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cornell_mixpanel':
      return '<p>' . t('Provides integration with the Mixpanel real-time analytics service. <strong>For more information, see the <a href="!docs_url" target="_blank">full documentation</a> online.</strong>', [
        '!docs_url' => 'https://drupal.org/node/2096053',
      ]) . '</p>';
  }
}
function cornell_mixpanel_preprocess_page(&$variables) {
  $config = \Drupal::config('cornell_mixpanel.settings');
  $found_domain = FALSE;
  $found_production_domain = FALSE;
  $found_non_production_domain = FALSE;
  $domains_to_track = $config->get('cornell_mixpanel_domains_to_track');
  if ($domains_to_track) {
    $domains_to_track = array_map('trim', explode(',', $domains_to_track));
    $current_domain = \Drupal::request()->getHost();
    if (in_array($current_domain, $domains_to_track)) {
      $found_domain = TRUE;
      $found_production_domain = TRUE;
    }
  }

  $non_prod_domains_to_track = $config->get('cornell_mixpanel_non_production_domains');
  if ($non_prod_domains_to_track) {
    $non_prod_domains_to_track = array_map('trim', explode(',', $non_prod_domains_to_track));
    $current_domain = \Drupal::request()->getHost();
    if (in_array($current_domain, $non_prod_domains_to_track)) {
      $found_domain = TRUE;
      $found_non_production_domain = TRUE;
    }
  }

  if (!$found_domain) {
    return;
  }

  $user = \Drupal::currentUser();
  if ($config->get('cornell_mixpanel_track_only_anonymous') && $user->isAuthenticated()) {
    return;
  }

  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($config->get('cornell_mixpanel_ignore_admin_routes') && strpos($route_name, 'admin') !== FALSE) {
    return;
  }

  $mixpanel_config = [];
  $proxy_config = $config->get('cornell_mixpanel_prod_proxy_domain');
  if ($proxy_config && $proxy_config != "") {
    $proxy_config = rtrim(trim($proxy_config), '/');
  }
  else {
    $proxy_config = "https://api-js.mixpanel.com";
  }
  $mixpanel_config['proxy_server'] = $proxy_config;

  if ($found_production_domain) {
    $mixpanel_config['token'] = trim($config->get('cornell_mixpanel_token'));
  }
  elseif ($found_non_production_domain) {
    $mixpanel_config['token'] = trim($config->get('cornell_mixpanel_test_token'));
  }
  else {
    // should never happen because of earlier check
    return;
  }

  $mixpanel_config['cross_subdomain_cookie'] = (bool) $config->get('cornell_mixpanel_cross_subdomain_cookie');
  $mixpanel_config['debug_mode'] = (bool) $config->get('cornell_mixpanel_debug_mode');
  $mixpanel_config['ignore_dnt'] = (bool) $config->get('cornell_mixpanel_ignore_dnt');
  $mixpanel_config['use_heatmap'] = (bool) $config->get('cornell_mixpanel_use_heatmap');

  $variables['#attached']['library'][] = 'cornell_mixpanel/cornell_mixpanel';
  $variables['#attached']['drupalSettings']['cornell_mixpanel'] = json_encode($mixpanel_config);
}
